version: "3.3"

networks:
  live_network:
    external: true
  internal_network:
    external: false

services:
  rallly:
    container_name: "rallly"
    image: lukevella/rallly:latest
    restart: unless-stopped

    networks:
      - "live_network"
      - "internal_network"

    depends_on:
      rallly-db:
        condition: service_healthy

    environment:
      - DATABASE_URL=postgres://postgres:postgres@rallly-db:5432/db

    env_file:
      - ./config/rallly.env  # TODO: Replace this with the location of your rallly env file.

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rallly-websecure.rule=Host(`rallly.example.com`)"  # TODO: Add your domain here
      - "traefik.http.services.rallly.loadbalancer.server.port=3000"
      - "traefik.http.routers.rallly-websecure.entrypoints=websecure"

  rallly-db:
    container_name: "rallly-db"
    image: postgres:14.2
    restart: unless-stopped

    networks:
      - "internal_network"

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

    volumes:
      - ./data/db-data:/var/lib/postgresql/data

    labels:
      - "traefik.enable=false"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
